name: Deploy to Hetzner on push
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H thirddegreemedia.com >> ~/.ssh/known_hosts
      - name: Push to server (triggers post-receive checkout)
        run: |
          git remote add prod ssh://orrin@thirddegreemedia.com/srv/git/thirddegreemedia.git
          git push prod HEAD:main --force-with-lease
